[package]
name = "schedule-parser-rusted"
version = "0.4.0"
edition = "2024"
publish = false

[dependencies]
actix-web = "4.10.2"
bcrypt = "0.17.0"
calamine = "0.26.1"
chrono = { version = "0.4.40", features = ["serde"] }
diesel = { version = "2.2.8", features = ["postgres"] }
diesel-derive-enum = { git = "https://github.com/Havunen/diesel-derive-enum.git", features = ["postgres"] }
dotenvy = "0.15.7"
fuzzy-matcher = "0.3.7"
jsonwebtoken = { version = "9.3.1", features = ["use_pem"] }
mime = "0.3.17"
objectid = "0.2.0"
regex = "1.11.1"
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = "3.12.0"
serde_repr = "0.1.20"
sha2 = "0.11.0-pre.5"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
rand = "0.9.0"

[dev-dependencies]
actix-http = "3.10.0"
criterion = "0.5.1"

[[bench]]
name = "parse"
harness = false
