[workspace]
members = ["lib/schedule_parser"]

[package]
name = "schedule-parser-rusted"
version = "0.3.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
schedule_parser = { path = "./lib/schedule_parser" }
chrono = "0.4.40"
reqwest = "0.12.15"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
