[workspace]
members = ["lib/schedule_parser"]

[package]
name = "schedule-parser-rusted"
version = "0.3.0"
edition = "2024"
publish = false

[dependencies]
bcrypt = "0.17.0"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"
diesel = { version = "2.2.8", features = ["postgres"] }
diesel-derive-enum = { git = "https://github.com/Havunen/diesel-derive-enum.git", features = ["postgres"] }
dotenvy = "0.15.7"
serde = { version = "1.0.219", features = ["derive"] }
schedule_parser = { path = "./lib/schedule_parser" }
chrono = "0.4.40"
reqwest = "0.12.15"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
actix-web = "4.10.2"
