[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
migration = { path = "migration" }
entity = { path = "entity" }
sea-orm = { version = "2.0.0-rc.15", features = ["sqlx-postgres", "runtime-tokio"] }

paste = "1"
serde = { version = "1", features = ["derive"] }