name: cargo test

on:
  push:
    branches: [ "master" ]
    tags-ignore: [ "release/v*" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test
        env:
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          SCHEDULE_DISABLE_AUTO_UPDATE: 1
          JWT_SECRET: "test-secret-at-least-256-bits-used"
          VK_ID_CLIENT_ID: 0
          VK_ID_REDIRECT_URI: "vk0://vk.com/blank.html"
          TELEGRAM_BOT_ID: 0
          TELEGRAM_MINI_APP_HOST: example.com
          TELEGRAM_TEST_DC: false
          YANDEX_CLOUD_API_KEY: ""
          YANDEX_CLOUD_FUNC_ID: ""